language: node_js
node_js: node
before_install: npm install -g grunt-cli
install: npm install
before_script: grunt publish_beta
branches:
  only:
  - none
env:
  matrix:
    secure: nVOPBKZUEQIjfntOp+4QOeIL3+Uz4FDSXJRhaYt6puULZfGh6NlwgplZTJ3JhPdXLIq4uVrGu4btfs3E6yR//sWen6CR9DLEiHNpQ2BDOFHxtFjE4mGkMHxex76BT3kZFuGUK99LgUutierbR8xbTLLSn/0onEMIYK7yDqY3+iK58C2IVeYQc3ipJZ+1l3MwxTNKK9e5T8X/nLxzdgyxGm5IFaZ8ggXa0yLOBz3N3l6Rs0jmz+sY47J2yFP3L2n6SOJZtSUpKBua9FSymZ552GOywZcy01fkKsbg7xbuITk40WI2KoZsLaRXvyt37xioYgyrO0HFH74gsEon1kPFntVPEa8EAFdpXbLYkQY2eExsjW5kjFO35kmOING1ZcU6NtzVMqMESRmHSl9Td2uuhFiuA8bDjrgaLYOgTjpr5ysz3x/57/QVHezSjk+FCrfF1kFBxYSZt9rc8+apSEHlDO3RxmRmZ/DMXpePy/irXrE0Xf5eK+zCiFC5iAjOG9hOgTbrDQpuy/HglGv1mr+BMhYy2nrWtthso/9nhYs2UdINwJhwyiGDtqRXZ5aQRv0M30cb4ubdYLEEjZENbeHDDeT8Mh1rw48yKudn8MBN6lD7iUTBJ/H1SgfHBxJL3dCv95PdZ0K9SmhsRScHQ7y20ApAyBJOj9qe9u+uDeckDFc=
