name: Verify CHANGELOG.md Updated
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/**'
      - 'src/data/**' # Ignore d2ai updates

jobs:
  changelog:
      if: github.event.pull_request.draft == false
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Labeled to Changelog:-None?
          id: haslabel
          uses: DanielTamkin/HasLabel@v1.0.4
          with:
            contains: 'Changelog-None'

        - name: Check for updates
          id: procelain
          uses: technote-space/get-diff-action@v4

        - name: Check for updates to CHANGELOG.md
          if: steps.haslabel.outputs.labeled-Changelog-None != true
          id: changelog_check
          uses: technote-space/get-diff-action@v4
          with:
            PATTERNS: |
              docs/CHANGELOG.md

        - name: No CHANGELOG.md Update (Remove Applied)
          if: (steps.changelog_check.outputs.insertions > 0 && steps.haslabel.outputs.labeled-Changelog-None != true)
          uses: mondeja/remove-labels-gh-action@v1
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            labels: |
              Changelog-Applied

        - name: No CHANGELOG.md Update (Add Missing)
          if: (steps.procelain.outputs.insertions > 0 && steps.changelog_check.outputs.insertions == 0 && steps.haslabel.outputs.labeled-Changelog-None != true)
          uses: christianvuerings/add-labels@v1
          with:
            labels: |
              Changelog-Missing
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: CHANGELOG.md Updated (Remove Missing)
          if: (steps.changelog_check.outputs.insertions > 0 && steps.haslabel.outputs.labeled-Changelog-None != true)
          uses: mondeja/remove-labels-gh-action@v1
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            labels: |
              Changelog-Missing

        - name: CHANGELOG.md Updated (Add Applied)
          if: (steps.changelog_check.outputs.insertions > 0 && steps.haslabel.outputs.labeled-Changelog-None != true)
          uses: christianvuerings/add-labels@v1
          with:
            labels: |
              Changelog-Applied
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


