name: 'Check spelling'
on: # rebuild on any PRs
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: streetsidesoftware/cspell-action@v1.0.1
        with:
          strict: false
          config: 'cspell.json'
