name: D2AI auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  d2ai-automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'd2ai-bot'
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          # required
          app-id:  ${{ secrets.AUTOMERGE_APP_ID }}
          private-key: ${{ secrets.AUTOMERGE_PRIVATE_KEY }}
      - name: Enable auto-merge for d2ai PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
