name: i18n-update

on:
  push:
    branches: [master]
    paths:
      - 'config/i18n.json'
      - 'src/locale/en.json'

jobs:
  i18n-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 3
          token: ${{ secrets.I18N_PAT }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Install
        run: yarn install --frozen-lockfile --prefer-offline

      - name: yarn i18n
        run: yarn i18n

      - name: Check for new files
        id: data
        run: echo ::set-output name=porcelain::"$(git status --porcelain)"

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.data.outputs.porcelain
        with:
          commit_message: Apply i18n updates
