name: i18n-update

on:
  push:
    branches: [master]
    paths:
      - 'config/i18n.json'
      - 'src/locale/en.json'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 3
          token: ${{ secrets.I18N_PAT }}

      - uses: ./.github/actions/setup-pnpm

      - name: Run i18n update
        run: pnpm i18n

      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "i18n: Apply automated updates"
